# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerald', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='father',
            new_name='father_id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='mother',
            new_name='mother_id',
        ),
    ]
