# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerald', '0003_auto_20180107_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='end_of_government',
            field=models.IntegerField(default=-1, verbose_name='Конец правления'),
        ),
        migrations.AddField(
            model_name='person',
            name='start_of_government',
            field=models.IntegerField(default=-1, verbose_name='Начало правления'),
        ),
    ]
